use_frameworks!

platform :ios, '8.0'

target 'LPMSNASiOS_Example' do
  pod 'LPMSNASiOS', :path => '../'

  target 'LPMSNASiOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
